steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/waahfood/puneetratan/waahfood:$SHORT_SHA', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/waahfood/puneetratan/waahfood:$SHORT_SHA']

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'waahfood', '--region=us-central1', '--platform=managed', '--image=gcr.io/waahfood/puneetratan/waahfood:$SHORT_SHA']

# TODO for auto authentication
# - name: 'gcr.io/cloud-builders/gcloud'
#   args: ['run', 'services', 'add-iam-policy-binding', 'SERVICE', '--member="allUsers"', '--region=us-central1',  '--role="roles/run.invoker"']
